### ISSUE TITLE
Run rendertron on AWS Elastic Beanstalk

### ISSUE THREAD

**Issue by pmaciejewski** [GoogleChrome/rendertron#103]
I'm struggling with running rendertron on AWS beanstalk as second container to my app. It is not possible to start the container in Dockerrun.aws.json version 2 due to security options not possible to set. Is it possible to bypass that? 

Example container setup

```
{
  "AWSEBDockerrunVersion": 2,
  "volumes": [],
  "containerDefinitions": [
    {
      (my app here)
    },
    {
      "name": "rendertron",
      "image": "ID.dkr.ecr.eu-central-1.amazonaws.com/rendertron:latest",
      "essential": true,
      "memory": 256,
      "links": [
        "static"
      ],
      "dockerSecurityOptions": [
        "label:seccomp:/root/chrome.json"
      ]
    }
  ]
}
```

**Comment by justinribeiro** [comment]
When you use `dockerSecurityOptions` on ECS, this requires telling the agent that that the `ECS_SELINUX_CAPABLE=true` or `ECS_APPARMOR_CAPABLE=true` environment variables are set before containers placed on that instance can use `--security-opt`. For EBS, my presumption is that this requires bootstrapping the instances the EB spins up with EC2 User Data to make that work. This is speculation on my part (as I have not tried this yet), but I suspect this is the problem based on your description.

Out of curiosity, if you spin up without the security options, what does EBS do? For instance, the container when run on GAE Flex doesn't spin up with the seccomp due to the nature of the way that GCP handles container security.

**Comment by pmaciejewski** [comment]
@justinribeiro yep, it were the flags. I was trying to set them on beanstalk level, not ECS. Now it seems ok. Thanks for help!

Without security options I couldn't find ANY information in the logs, it was really confusing.
