### ISSUE TITLE
Render to PDF

### ISSUE THREAD

**Issue by sshcherbakov** [GoogleChrome/rendertron#137]
Hello there,

Thank you for this project! And sorry for asking questions about Rendertron in a GitHub ticket, please let me know a better way to do that. 

From several other alternative options out there like
https://github.com/zenato/puppeteer-renderer
https://github.com/cheeaun/puppetron
that promise rendering into PDF format, none supports Web Components v1 (Polymer 2.2.0) based application that I need to get a platform independently rendered PDF page for.

The Rendertron is the only one that I have succeeded to render our Polymer based application pages so far (kudos!).

My problem is that I don't find an option to generate a [multi-page] PDF document using the Rendertron.

As an intermediate workaround the Rendertron's "screenshot" feature would do if it could only generate screenshots in higher resolution than the default one. Is there a way to control the resulting JPEG quality/resolution?

Thank you!

**Comment by samuelli** [comment]
Thanks for filing an issue. Initially, we had PNG screenshots which are lossless, but they ended up being too large, so it was switched to lower resolution JPEGs.

We can probably just add PDF rendering to Rendertron.

**Comment by sshcherbakov** [comment]
This would be an incredibly useful feature for us.
I was going to investigate the way of merging the PDF rendering capability of the other projects with this one, but it is amazing how fast this ticket has been addressed, thank you!
(Can't wait for PR to pass the build)

**Comment by sshcherbakov** [comment]
Just tried out the PR and it looks good!

**Comment by samuelli** [comment]
Hi @sshcherbakov,

I've actually closed the PR instead of merging it. I've thought about this issue more and realised this is not necessary for Rendertron. Where Rendertron is required regarding web components is around serializations. Any headless Chrome solution uses Chrome and thus supports web components. Puppeteer will be able to generate PDFs for a page that uses web components, but will not be able to serialize it.

I thought about adding it to Rendertron anyway, but it seems better to keep Rendertron simple. You're welcome to manually use the PR I created to use it.

Thanks.
