### ISSUE TITLE
What are the hosting container "hardware" requirements?

### ISSUE THREAD

**Issue by jonathanfishbein1** [GoogleChrome/rendertron#171]
What are the optimal number of cores and memory requirements for the container hosting rendertron?

**Comment by Romanchuk** [comment]
Same question

**Comment by AVGP** [comment]
That depends on the number of parallel requests you're dealing with as well as the memory and CPU consumption of each browser tab rendering your pages. So that's very hard to answer.

I'd say: Observe the consumption of a locally-running Rendertron instance under the load conditions you'll have when deployed and use that.
