### ISSUE TITLE
Cannot render URL - Docker logs { message: 'net::ERR_CONNECTION_REFUSED' }

### ISSUE THREAD

**Issue by nhducseuit** [GoogleChrome/rendertron#177]
I'm on MacOS sierra and follows the guide at https://angularfirebase.com/lessons/seo-angular-part-1-rendertron-meta-tags/ for getting start with rendertron.
However I got error `cannot render URL` when I try at my local. Docker logs `{ message: 'net::ERR_CONNECTION_REFUSED' }` whenever I try to render or screenshot the tour of heroes project launching with `ng serve`
I checked and tried the suggestions at https://github.com/GoogleChrome/rendertron#connection-error-econnrefused but none of them works.

I have done following commands:
```
git clone https://github.com/GoogleChrome/rendertron.git server
cd server

docker build -t rendertron . --no-cache=true

docker run -it -p 8080:8080 --name rendertron-container rendertron
```

**Comment by hekod777** [comment]
I am using macOS as well. The solutions in the readme worked for me.

In some OSS you may consider adding --no-sandbox flag to start chrome to avoid connection refused error. 

```
chromeFlags: ['--headless', '--disable-gpu', '--remote-debugging-address=0.0.0.0', '--no-sandbox']
```

**Comment by nhducseuit** [comment]
Thanks for the response @hekod777 
I tried adding `--no-sandbox` option to chrome-launcher in main.js and rebuilt the image, but the error is still there.
I also tried to use --cap-add SYS_ADMIN without success.
Do you know how should I debug this issue?

**Comment by hekod777** [comment]
@nhducseuit If you have tried
```
[Recommended] - Use Jessie Frazelle' seccomp profile and -security-opt flag
```
as well.

Then there is not much else come into my mind.

Even on AWS, I fixed this connection refused error with a combination of `-security-opt` + `--no-sandbox`. My guess is that maybe it's something other than rendertron itself.


and try to render some pages other than the tour of heroes app. When I tested it a while back, rendertron failed to render it due to some fake async call.

**Comment by aakashbanerjee** [comment]
Hello Folks I am facing the same dreaded ERR_CONNECTION_REFUSED issue. I built a AWS EC2 instance from scratch and installed everything and deployed Rendertron on that instance. Here is how I did that - https://medium.com/@aakashbanerjee/deploying-rendertron-on-aws-ec2-8c00a4bb6b1e
Now using rendertron express js middleware I am routing all bot requests to the ec2 server where rendertron lives. I tested it trying to create a facebook share post and the request was correctly routed to the ec2 server with rendertron. However the rendertron server displays this message.

Cannot render requested URL
{ message: 'net::ERR_CONNECTION_REFUSED' }

Since I did not use a docker image where can I set the chromeFlags or how do I go about using the security opt flag using jessie frazell's recommended seccomp profile? Any help is much appreciated.

Thanks.

**Comment by aakashbanerjee** [comment]
Update: AWS EC2 Ubuntu 16.04 LTS instance deployed with docker container. Same issue ERR CONNECTION REFUSED.
Chrome launched with debugging on port 45630
Listening on port 8080
Cannot render requested URL
{ message: 'net::ERR_CONNECTION_REFUSED' }

I tried running the container with recommended jessie frazelle --security-opt flag 
sudo docker run -it -p 8080:8080 --security-opt seccomp=$HOME/chrome.json --name rendertron-container rendertron

Also tried running the container with --cap-add SYS_ADMIN
sudo docker run -it -p 8080:8080 --cap-add SYS_ADMIN --name rendertron-container rendertron

I also tried running the docker container using this below:
sudo docker run -it -p 8080:8080 --security-opt seccomp=$HOME/chrome.json --cap-add SYS_ADMIN --name rendertron-container rendertron

> rendertron@1.1.1 start /app
> node src/main.js

Chrome launched with debugging on port 38166
Listening on port 8080

I used the rendertron express middleware on my nodejs server on another EC2 machine like this.

const rendertron = require('rendertron-middleware');
if(process.env.NODE_ENV !== 'production'){
  app.use(rendertron.makeMiddleware({
    proxyUrl: 'http://rosiepytron.rosiepy.com:8080/render',
  }));
}

Now if I try to post a tweet on twitter  with just https://dev.rosiepy.com I see the log below on my nodejs server where my middleware is:

1|server   | [rendertron middleware] ECONNREFUSED error fetching http://rosiepytron.rosiepy.com:8080/render/http%3A%2F%2Fdevapi.rosiepy.com%2F

Posting on facebook doesnt even trigger a response for some reason.

In rendertron/src/main.js the chrom launcher flags are as below.

const appPromise = chromeLauncher.launch({
  chromeFlags: ['--headless', '--no-sandbox', '--remote-debugging-address=0.0.0.0'],
  port: 0
}).then((chrome) => {
  console.log('Chrome launched with debugging on port', chrome.port);
  config.chrome = chrome;
  config.port = chrome.port;

Interestingly 

If I just hit the following on the chrome browser it renders fine without images thats probably some other problem for the images.
http://rosiepytron.rosiepy.com:8080/render/https%3A%2F%2Fdevapi.rosiepy.com%2F

If you just hit http://rosiepytron.rosiepy.com:8080/ rendertron comes up fine and the screenshot and render/serialize works but somehow the api render gives connection refused.

Any help would be much appreciated.

**Comment by chirayu25** [comment]
I am also facing same issue. Is any one able to solve this??

**Comment by AVGP** [comment]
We're no longer officially supporting the Docker deployment path at the moment.
