### ISSUE TITLE
Q: Concerning Blackhat SEO

### ISSUE THREAD

**Issue by bm-stschneider** [GoogleChrome/rendertron#179]
Does rendertron fall into the practice of so-called blackhat SEO or not? Since if you check for crawlers and server-side render components with puppeteer/headless chrome is this sanctioned practice according to google search engine indexing rules?

**Comment by samuelli** [comment]
Hi @bm-stschneider,

Rendertron is designed to fill the gaps for agents that don't render webpages. [Googlebot does](https://developers.google.com/search/docs/guides/rendering) render your page, so that is the preferred solution when serving to googlebot.

You may use Rendertron with Googlebot if you wish, but we do not recommend it and it is excluded from our user agent check. If you're using Polymer, check out my article on using it with Googlebot. https://medium.com/dev-channel/polymer-2-and-googlebot-2ad50c5727dd

I hope that answers your question.

Thanks.

**Comment by bm-stschneider** [comment]
Not to the full extend. Would I run into problems when I use rendertron to hydrate the webpage for Googlebot when I use Vue/React/Polymer/Angular/etc. ?

**Comment by samuelli** [comment]
I'm unable to answer that question. Please refer to https://developers.google.com/search/docs/guides/rendering

**Comment by samuelli** [comment]
For more context, it's our policy to provide honest search results and we cannot provide further information about how this works. All the information we can provide is publicly documented. Please also make use of the official tools such as [Fetch as Google](https://support.google.com/webmasters/answer/6066468?hl=en)

**Comment by gravi2** [comment]
I now notice that Google is recommending using rendertron in the documentation, for dynamic rendering. So I guess this is not considered Blackhat SEO. 
https://developers.google.com/search/docs/guides/dynamic-rendering

**Comment by AVGP** [comment]
Hi, I'm the one who wrote the dynamic rendering guide mentioned by @gravi2 - dynamic rendering is a workaround we officially support and Bing has also signalled that they're fine with it.

Unless you do something to mislead your users (cloaking), you're fine :)

**Comment by bm-stschneider** [comment]
What is cloaking in this context?

**Comment by AVGP** [comment]
Say your website is about selling boats, but you'd show a website about cute kittens to the crawler. That is cloaking. As long as you don't mislead your users, using Rendertron is fine.

**Comment by bm-stschneider** [comment]
ah ok.
