### ISSUE TITLE
Disk Cache?

### ISSUE THREAD

**Issue by villanus** [GoogleChrome/rendertron#207]
Is it posible to cache pre-rendered urls to disk?  Or aws s3,  google cloud storage or azure files?   I want to pre-render pages on the fly (via url calls) but then store them in cloud.   This would allow using nginx as a reverse proxy to serve generated pages from cloud storage when they exist otherwise using rendertron to build the static page and store it for future hits.

**Comment by ford442** [comment]
That is what I am trying to do as well. It says in the comments that this function was not written into the script, but is left for us users to program.
If you set up the cache=true option from the default instructions then it will start to cache into the Google Datastore, but I haven't found how to use that data easily yet.

**Comment by yctn** [comment]
im trying to do this aswel. anyone got this to work?

**Comment by reedzhao** [comment]
> This would allow using nginx as a reverse proxy to serve generated pages

Why not use nginx to cache the pages on disk?  I am doing it.

**Comment by frontendr** [comment]
My question is if this is should really be a part of this package. Shouldn't it be the job of some middleware which is requesting the render? Maybe write some tutorials on how to do it using different applications as @reedzhao did with NGINX. This way we can keep this package 'clean' and 'unopinionated' on how to store any renditions.

I suggest to let it do one thing and one thing good and that's rendering pages (with specific settings) and returning the results.

**Comment by AVGP** [comment]
I agree with @frontendr especially as file systems bring various settings and potential issues (e.g. permission problems) with them. If someone wants to build this and customize Rendertron with it then feel free to look into the https://github.com/GoogleChrome/rendertron/blob/master/src/datastore-cache.ts file. Instead of calling the datastore, you'd have to implement the `cacheContent` and `middleware` methods to use the file system
