### ISSUE TITLE
Angular 6 Ionic 4 rendering goes wrong

### ISSUE THREAD

**Issue by HelgeWieding** [GoogleChrome/rendertron#259]
Hi, 

I have an application that is using ionic ```4.0.0-beta.15-0``` & ``` angular 6.1.10```.

The rendering is broken and looks like this. 

![image](https://user-images.githubusercontent.com/754426/50803219-1e35cb80-12ea-11e9-83bd-b403121aa22f.png)

where as without rendertron it renders correctly 

![image](https://user-images.githubusercontent.com/754426/50803237-34438c00-12ea-11e9-9579-894723c69cab.png)

It does not seem to be an issue with the render time budget as the page always is shown in the same broken state. (i tried window.renderComplete event) 
The async calls have completed and in the serialized version all the dom nodes that should be there are there. 
Though i noticed the shadow-dom nodes are missing. Is this maybe the issue? It wasnt quite clear to me as how i enable shady-dom as i am not using polymer or any web-components lib for that matter. Ionic4 might use them under the hood though.

**Comment by tehXor** [comment]
I'm seeing similar problems with Ionic 4 & Angular 7. Definitely no time budget/async problem since for example `screenshot` instead of `render` returns correct screenshots. However I would fear crawlers will ignore content also it is present in the serialized code since it is not visible due to broken css/shadow dom. I couldn't find a workaround so far with for example the available rendertron parameter for shadow dom.

**Comment by AVGP** [comment]
Do you have that page online somewhere or could you give us a demo app with Ionic 4 & Angular 7 that exposes that problem?

**Comment by AVGP** [comment]
Feel free to reopen this issue with more information how to reproduce the problem.
