### ISSUE TITLE
progress-bar.html not found

### ISSUE THREAD

**Issue by abdonrd** [GoogleChrome/rendertron#360]
Rendertron used to have a progress bar while waiting for the rendering
https://github.com/GoogleChrome/rendertron/blob/3b75d5b7dfc4ceac47bb30568f417a4fc2b6a9b9/src/index.html#L237

This file doesn't exist anymore and we should replace it with a simple [HTML progress element](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/progress).

**Comment by AVGP** [comment]
I guess we can just remove this, then. As far as I can tell that file hasn't existed since at least 2017.

**Comment by abdonrd** [comment]
I just saw that this does exist in several places:

<img width="343" alt="Screenshot 2020-01-08 at 14 57 19" src="https://user-images.githubusercontent.com/1007051/71983530-491d6d00-3227-11ea-9c35-5ca318ca52d9.png">

**Comment by abdonrd** [comment]
I just tried to replace the path with the dependency path:

`node_modules/progress-bar-element/progress-bar.html`

But it doesn't work. What is the correct way to import a npm dependency into this project?

**Comment by AVGP** [comment]
The fundamental problem here is that it uses a webcomponent which is imported via HTML imports. Those are deprecated and we'd need to find out how to implement this properly.

On top of that, Sam doesn't seem to maintain the progress bar anymore (last change was 3 years ago).

I think it's a nice-to-have, so I would turn this issue into a way for a new contributor to provide us with a simple HTML progress bar instead of using any additional dependency.

**Comment by richardhofmaenner** [comment]
Hi @AVGP, I think this issue can be closed. It was related to pr #384
