### ISSUE TITLE
Create best practices documentation

### ISSUE THREAD

**Issue by AVGP** [GoogleChrome/rendertron#393]
Right now, there is no "docs/best_practices.md" file.
Create this file and describe the best practices for running Rendertron. Some to get started:

- Run Rendertron behind a firewall or proxy with authentication, because it does not provide an authentication layer.
- Enable caching to speed up the response times
- Regularly pre-warm the cache by requesting a render for your most important URLs to make sure that bots get a quick response

**Comment by hheexx** [comment]
I recommend running rendertron at reverse proxy level, not using middleware.
Because if you use it as middleware and you have reverse proxy in front of it you can not cache pages without having bot detection logic in reverse proxy. If you have bot detection logic in reverse proxy then it makes sense to have it only there for clear separation of concerns. Duplicate code is always pain.

Comments?


we should add link in readme to good nginx config for example this one https://gist.github.com/justindavies/7421d1f112f5c1b606dd27f4fcd8a856#file-nginx-rendertron-conf

**Comment by AVGP** [comment]
We do have new docs coming - you can take a look at it in the `docs` folder.
