### ISSUE TITLE
Question: Why googlebot is not on a list of user agents?

### ISSUE THREAD

**Issue by adelura** [GoogleChrome/rendertron#397]
First, thank you for such a cool tool! I managed to implement _rendertron_ successfully on my page :+1:

I'm sorry for asking a dumb question, but why _Googlebot_ is not on the list below? Does it mean that my pages won't server prerendered version for google crawler?

https://github.com/GoogleChrome/rendertron/blob/master/middleware/src/middleware.ts#L24

**Comment by AVGP** [comment]
Hi, @adelura - thanks for asking!
Googlebot can execute JavaScript and usually doesn't need dynamic rendering like Rendertron provides. That's why Googlebot can be added to the list, if you decide to do so but is not part of the default list of bots.

See [this earlier comment](https://github.com/GoogleChrome/rendertron/pull/258#issuecomment-453104073) for more background.
