### ISSUE TITLE
I have to scrap url multiple times via share debugger, when page is rendered via rendertron

### ISSUE THREAD

**Issue by devGitAbhishek** [GoogleChrome/rendertron#399]
Hi,

I have to scrape multiple times the url via share debugger?

I know facebook caches, but i have to scrap multiple times, i am seeing in logs body send via rendertron is updated one but not getting updated in facebook?

Any workaround this?

**Comment by devGitAbhishek** [comment]
This is happening only in case of facebook,twitter works fine.

**Comment by devGitAbhishek** [comment]
@AVGP any help would be appreciated?

**Comment by AVGP** [comment]
If this works with Twitter's validator, the problem is likely with the Facebook validator.
I'm assuming you can append query parameters to the URL in order to try and circumvent their caching?

Let's say you are trying the url `https://example.com/some-post`, then append an unused parameter and keep changing the value, so for example you'd try `https://example.com/some-post?dontcachethisfacebook=1` then `https://example.com/some-post?dontcachethisfacebook=2` - if you are lucky, Facebook considers these different URLs and won't cache them.
