### ISSUE TITLE
Website has css missing and API calls don't get fulfilled when rendering it through Rendertron 

### ISSUE THREAD

**Issue by yash9919** [GoogleChrome/rendertron#803]
We want to integrate rendertron with our React application for SEO optimisation and we were checking how rendentron renders the application - https://render-tron.appspot.com/render/http://uranai.rakuten.co.jp/

Seems like it is not able to load some css files and API calls to our backend services are also failing as I can see error messages. 

What could be the reason behind this behaviour and how can we fix it?
<img width="1178" alt="Screenshot 2021-10-06 at 9 32 16 AM" src="https://user-images.githubusercontent.com/52064558/136139037-4eef647a-273e-4cfb-8134-8311e2736a6a.png">

**Comment by zehawki** [comment]
> Seems like it is not able to load some css files

You can open the generated HTML in some editor. You may see that it links to the current CSS bundle from existing website. After a while, this CSS bundle may no longer be available on your website, since the hash may have changed with a rebuild. Perhaps this is the issue.

Note that for SEO (spiders, crawlers), the CSS being present or not should have no significance.

**Comment by AVGP** [comment]
In general, as we're deprecating the project, you should look into alternative approaches to [rendering on the web](https://web.dev/rendering-on-the-web/).
